# Discord link

discord: "discord.gg/yourlink"

# Shop Link

shop: "shop.link"

# Navigator Items & IPs

SwordItemIP: "yourip.ip"
SwordItemName: "Name1"
BowItemIP: "yourip.ip"
BowItemName: "Name2"
GAppleItemIP: "yourip.ip"
GAppleItemName: "Name3"

# Motion Buff Item (Just put "368" for ENDER_PEARL or "332" for SnowBall)

MotionBuffItem: "368"
